esphome:
  name: piscine

esp32:
  board: esp32-c3-devkitm-1

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: ""

mdns:

time:
  - platform: sntp
    id: my_time
    timezone: Europe/Paris

wifi:
  ssid: "xxxxxxxxxxxxxxx"
  password: "xxxxxxxxxxxxx"
  
sensor:
  - platform: dallas_temp
    address: 0xca00000046992a28
    name: temperature
    update_interval: 60s
    filters:
      - lambda: return x + 2.0; 

deep_sleep:
  id: deep_sleep_1

interval:
  - interval: 1min
    then:
      - if:
          condition:
            lambda: |-
              auto now = id(my_time).now();
              return now.is_valid() && now.hour == 0 && now.minute == 0;
          then:
            - deep_sleep.enter:
                id: deep_sleep_1
                sleep_duration: 25200s  # 7 heures

logger:
  level: INFO  
  baud_rate: 115200  
  logs:
    sensor: INFO          
    one_wire.gpio: INFO    

one_wire:
  - platform: gpio
    pin: GPIO4
    id: bus_ds
